# This is part of a GNU-Makefile, to specify system-dependent 
# parts of the Makefile enviroment.
#
# This gets included as part of the GNU-Makefile used in each of 
# the subdirectories.
#
# Depending on your platform, you need to select the correct definition.
# Also, you need to edit the Makefile in the bin subdirectory.

# Linux i386 (default)
# HOST = -DHOST_i386 -DHOST_LINUX
# CPP=gcc

# Linux x86_64
HOST = -DHOST_x86_64 -DHOST_LINUX
CPP=gcc

# SUN SPARC, Sun 4.xx (not supported, just to show how to declare a
# big-endian processor)
# HOST = -DHOST_SPARC -DHOST_IS_BIG_ENDIAN

# 386, 386BSD Unix, or NetBSD Unix (available via anon ftp 
#    from agate.berkeley.edu)
# HOST = -DHOST_i386
# CPP=/usr/bin/cpp

# slight variant for 386 FreeBSD
# HOST = -DHOST_i386 -DHOST_FreeBSD
# CPP=/usr/bin/cpp


